=== pchapin/rml/RML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- FILE    : RML.xsd
     AUTHOR  : (C) Copyright 2020 by Peter C. Chapin <peter@pchapin.org>
     SUBJECT : XML schema for describe recipes.
     
     TODO:
     
     + Some facility for recording references (to cookbooks, online URLs, or people) should be
       provided. Perhaps a references element consisting of a list of reference elements. Each
       reference could have an ID that a recipe uses to link itself to a particular reference.
       This puts all reference information into a single place where it can be more easily
       maintained.
       
     + Some facility for storing the contact information of people making comments should be
       provided.
       
     + Some way to indicate which ingredient in a list of alternatives is primary should be
       provided. Also it should be possible to mark some ingredients as "non-essential" meaning
       the recipe can be made successfully without them if necessary.
-->

<xs:schema targetNamespace="http://www.pchapin.org/XML/RML"
  xmlns="http://www.pchapin.org/XML/RML" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xhtml="http://www.w3.org/1999/xhtml" elementFormDefault="qualified" xml:lang="en-US">

  <xs:annotation>
    <xs:documentation>This is a schema that defines the XML format used for describing
      recipes.</xs:documentation>
  </xs:annotation>

  <!-- ROOT ELEMENTS -->

  <xs:element name="recipe-list">
    <xs:annotation>
      <xs:documentation>A container for a collection of recipes.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recipe" type="recipeType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="recipe" type="recipeType">
    <xs:annotation>
      <xs:documentation>This element contains information about exactly one
        recipe.</xs:documentation>
    </xs:annotation>
  </xs:element>


  <!-- COMPLEX TYPES -->

  <xs:complexType name="recipeType">
    <xs:annotation>
      <xs:documentation>Describes the structure of a recipe.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="description" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:any namespace="http://www.w3.org/1999/xhtml" processContents="lax" minOccurs="0"
              maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ingredients" type="ingredientsType"/>
      <xs:element name="cooking-instructions" type="cookingInstructionsType" minOccurs="0"/>
      <xs:element name="instructions" type="instructionsType" minOccurs="0"/>
      <xs:element name="serves" minOccurs="0" type="xs:string"/>
      <xs:element name="comments" type="commentsType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  
  
  <xs:complexType name="ingredientsType">
    <xs:annotation>
      <xs:documentation>Describes a collection of ingredients.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="ingredient" type="ingredientType"/>
        <xs:element name="alternatives" type="alternativesType"/>
        <xs:element name="section" type="ingredientsSectionType"/>
      </xs:choice>     
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="ingredientType">
    <xs:annotation>
      <xs:documentation>Describes a single ingredient.</xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="quantity" type="xs:float"/>
        <xs:attribute name="units" type="unitsType"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:complexType name="alternativesType">
    <xs:annotation>
      <xs:documentation>Describes a collection of ingredients that can be substituted for one
        another. Elements of this type can be used in places where a single ingredient is
        expected. Any one of the alternatives mentioned such an element stands as one
        ingredient in an overall list of ingredients.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ingredient" type="ingredientType" minOccurs="2" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="ingredientsSectionType">
    <xs:annotation>
      <xs:documentation>Describes a section of related ingredients.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="ingredient" type="ingredientType"/>
        <xs:element name="alternatives" type="alternativesType"/>
        <xs:element name="section" type="ingredientsSectionType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"/>
  </xs:complexType>


  <xs:complexType name="cookingInstructionsType">
    <xs:annotation>
      <xs:documentation>Describes the specifics of how to cook the recipe. Elements of this
        type are not intended to cover the details of preparation (elements of type
        instructionsType can be used for that). Elements of this type only cover the actual
        cooking itself.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="summary" minOccurs="0">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="time" type="xs:duration" use="required"/>
              <xs:attribute name="temperature" type="temperatureType" use="required"/>
              <xs:attribute name="units" type="temperatureUnitsType"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="notes" type="commentsType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="instructionsType">
    <xs:annotation>
      <xs:documentation>Describes a collection of instructions.</xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="step" type="xs:string" maxOccurs="unbounded"/>
      <xs:element name="section" type="instructionsSectionType"/>
    </xs:choice>
  </xs:complexType>
  
  
  <xs:complexType name="instructionsSectionType">
    <xs:annotation>
      <xs:documentation>Describes a section of related instructions.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="step" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="section" type="instructionsSectionType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name"/>
  </xs:complexType>
  
  
  <xs:complexType name="commentsType">
    <xs:annotation>
      <xs:documentation>This type gives general comments from the taste
        testers.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="comment" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:any namespace="http://www.w3.org/1999/xhtml" processContents="lax" minOccurs="0"
              maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="author" type="xs:string"/>
          <xs:attribute name="date" type="xs:date"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


  <!-- SIMPLE TYPES -->

  <xs:simpleType name="specificUnitsType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="15oz can"/>
      <xs:enumeration value="28oz can"/>
      <xs:enumeration value="cloves"/>
      <xs:enumeration value="cup"/>
      <xs:enumeration value="gram"/>
      <xs:enumeration value="large"/>
      <xs:enumeration value="lb"/>
      <xs:enumeration value="leaf"/>
      <xs:enumeration value="medium"/>
      <xs:enumeration value="oz"/>
      <xs:enumeration value="small"/>
      <xs:enumeration value="sprigs"/>
      <xs:enumeration value="tbsp"/>
      <xs:enumeration value="tsp"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="userDefinedUnitsType">
    <xs:restriction base="xs:string">
      <xs:pattern value="user!.*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="unitsType">
    <xs:union memberTypes="specificUnitsType userDefinedUnitsType"/>
  </xs:simpleType>

  <xs:simpleType name="temperatureUnitsType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="C"/>
      <xs:enumeration value="F"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="temperatureType">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="100"/>
      <xs:maxInclusive value="500"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== pchapin/rml/RML-sample.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="RML.xsl"?>

<!-- FILE    : RML-sample.xml
     AUTHOR  : Peter C. Chapin <PChapin@vtc.vsc.edu>
     SUBJECT : Example RML document. -->

<recipe-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vtc.edu/XML/RML RML.xsd http://www.w3.org/1999/xhtml http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd"
  xmlns="http://www.vtc.edu/XML/RML" xmlns:xhtml="http://www.w3.org/1999/xhtml">

  <recipe name="Chocolate Chip Cookies">
    <ingredients>
      <ingredient quantity="1" units="cup">White flour</ingredient>
      <ingredient quantity="0.5" units="user!stick">Butter</ingredient>
      <ingredient quantity="16" units="oz">Chocolate Chips</ingredient>
    </ingredients>
    <cooking-instructions>
      <summary time="PT00H05M12.2334S" temperature="200" units="F"/>
      <notes>Be sure the cooking time is followed exactly.</notes>
    </cooking-instructions>
    <instructions>
      <step>Mix</step>
      <step>Bake</step>
      <step>Eat</step>
    </instructions>
  </recipe>

  <recipe name="Cupcakes">
    <ingredients>
      <ingredient quantity="1" units="cup">Whole Wheat Flour</ingredient>
    </ingredients>
    <cooking-instructions>
      <summary time="PT1S" temperature="200" units="F"/>
    </cooking-instructions>
    <instructions>
      <step>Eat</step>
    </instructions>
  </recipe>

</recipe-list>
